#pragma once


#define MESSAGE_DISCONNECT 1
#define MESSAGE_ANSWER 2
#define MESSAGE_PING 3
#define MESSAGE_NAME_TAKEN 4
#define MESSAGE_REGISTERED 5
#define MESSAGE_HELLO 6

#define MAX_TEXT_SIZE 50000
#define CLIENT_NAME_SIZE 128